### ISSUE TITLE
Greater than operator doesn't work with equality

### ISSUE THREAD

**Issue by null77** [erstan/ceval#3]
"1 > 1" returns true, if I debugged correctly:

ceval_lesser seems to not be returning the correct result when the values are equal. (b - a) >= CEVAL_EPSILON; -> 0 > 1e-2, which is false.

**Comment by erstan** [comment]
| Expression | Result | Expected Result |
| ------------| ----------- |---------------|
| 1>1      | 1.000000       | 0.000000 |
| 1>=1   | 0.000000      |1.000000       | 
| 1<1      | 1.000000       | 0.000000 |
| 1<=1   | 0.000000      |1.000000   | 

As is evident from the test cases above, the (`>` ,`<`) operators are behaving like the (`>=` ,`<=`) operators, and vice-versa.
It seems like in the attempt of having named my functions for the `<=` and `>=` operations, rather confusingly as `ceval_lesser()` and `ceval_greater()`, I mis-defined them for their strict counterparts ( `ceval_lesser_s()` and `ceval_greater_s()` ). 

I [fixed the function definitions](https://github.com/erstan/ceval/commit/c737c892f624f3ab59b8d617a318e13b163c8022) and the inequality operators appear to be working normally. 
```
In = 1<1
Out = 0.000000

In = 1<=1
Out = 1.000000

In = 1>1
Out = 0.000000

In = 1>=1
Out = 1.000000

In = 0<1e-2 
Out = 1.000000
```
