### ISSUE TITLE
C++ segmentation fault

### ISSUE THREAD

**Issue by qiray** [erstan/ceval#5]
It looks like the lib doesn't work in C++ even in example file. I use g++ and example from Readme and get segmentation fault.

**Comment by erstan** [comment]
Thanks for reporting this massive bug. Sorry for the inconvenience. I would need to track down how this silly type conversion (<https://github.com/erstan/ceval/commit/4746f684f1dc95542611c3d412e37afde7d8392d>) got into my code without me ever spotting it. I guess I would also need to work on a set of unit tests (or someone else needs to) to check that everything is working fine after every update. 

Do close the issue if it works fine now.

**Comment by qiray** [comment]
It works now. Thank you for this extremely fast fix. :-)

Don't forget to fix this bug in https://github.com/erstan/ceval-single-header
